import Mandelbrot from "@/components/Mandelbrot";

export const metadata = { title: "Origins" };

export default function Origins() {
  return (
    <main id="main" className="min-h-screen bg-emerald-950 text-white px-6 pt-28 pb-20">
      <article className="mx-auto max-w-2xl">
        <h1 className="text-4xl font-bold [font-family:var(--font-atkinson)]">Origins</h1>
        <p className="mt-8 space-y-4 text-lg leading-relaxed text-emerald-50">
        The Unmapped is a research and essay series exploring accessibility gaps in AI and 
        the technology built around it. It exists because brilliant friends, through their 
        lived experience, questions, and refusal to accept these gaps as permanent, charted 
        them for me in the first place. I mostly just write them down.
        </p>
        <p className="mt-4 text-lg leading-relaxed text-emerald-50">
        We strive to meet WCAG AAA accessibility standards across this site. If anything falls 
        short, or is simply bugging you, <a href="mailto:kristi.eaton@columbia.edu" aria-label="Report an accessibility issue by email" className="underline underline-offset-4 hover:text-white">
        please let us know.
          </a>
        </p>
        <section className="mt-12 border-t border-emerald-800 pt-8">
        <h2 className="text-xl font-bold text-emerald-300 [font-family:var(--font-atkinson)]">
            Mandelbrot Fractals
          </h2>
        <p className="mt-10 text-lg leading-relaxed text-white">
        The fractal below is the Mandelbrot set, named for mathematician Benoît Mandelbrot. He 
        showed that self-repeating patterns appear throughout nature and helped develop the 
        mathematics used to describe them. The Mandelbrot set is the best-known example: 
        infinitely detailed at every scale, yet generated by repeatedly applying the equation 
        z<sub>n+1</sub> = z<sub>n</sub><sup>2</sup> + c. It reflects The Unmapped: revealing 
        structures that are easy to overlook.
      </p>
        <div className="mt-12 h-[60vh]">
          <Mandelbrot />
        </div>
        </section>
        <section className="mt-12 border-t border-emerald-800 pt-8">
        <h2 className="text-2xl font-bold text-emerald-300 [font-family:var(--font-atkinson)]">
            About the author
          </h2>
          <p className="mt-3 text-base leading-relaxed text-emerald-100">
            Kristi Lyn Eaton is a writer, technologist, and experience designer with continued
            computer science studies at Columbia University. Her work brings together emerging technology, 
            accessibility, and advocacy, drawing on a background in nonprofit leadership and 
            experiential design, and robotics research at Columbia's ROAR Lab. The Unmapped is where she 
            connects those threads.
          </p>
        </section>
      </article>
    </main>
  );
}