import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <nav className="fixed top-0 z-20 w-full bg-emerald-950/80 backdrop-blur-sm px-6 py-4 flex gap-6">
          <Link href="/" className="font-bold text-white">The Unmapped</Link>
          <Link href="/beams/tokenization" className="text-emerald-100">Tokenization</Link>
          <Link href="/beams/screen-readers" className="text-emerald-100">Screen Readers</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
